### ISSUE TITLE
Unable to install sinch-rtc from npm with xCode 7.1

### ISSUE THREAD

**Issue by JeanLebrument** [sinch/sinch-js-rtc#1] opened 2015-11-09 10:22 UTC
Hello,

I have some troubles when installing `sinch-rtc` through npm (`npm install --save sinch-rtc`) using xCode 7.1

Here are the logs from npm: 

```
Jean: ~/Developments/SendMessageToContact  npm i sinch-rtc --save
npm WARN engine agentkeepalive@0.2.4: wanted: {"node":"0.10.x"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN prefer global node-gyp@1.0.3 should be installed with -g

> wrtc@0.0.55 install /Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

2015-11-09 10:44:33.929 xcodebuild[8819:66310] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/QuickLocalization.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-09 10:44:33.930 xcodebuild[8819:66310] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUDebuggerTuckAway.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=darwin CONFIGURATION=Release PYTHON=python MODULE_PATH=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (170 bytes)
POST git-upload-pack (179 bytes)
remote: Counting objects: 938, done
remote: Finding sources: 100% (938/938)
remote: Total 938 (delta 88), reused 522 (delta 88)
Receiving objects: 100% (938/938), 4.68 MiB | 6.58 MiB/s, done.
Resolving deltas: 100% (88/88), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (170 bytes)
POST git-upload-pack (179 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1804), reused 9928 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 4.58 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking connectivity... done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.6M  100 20.6M    0     0  2905k      0  0:00:07  0:00:07 --:--:-- 4511k
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
2015-11-09 10:44:54.147 xcodebuild[9167:67154] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/QuickLocalization.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-09 10:44:54.148 xcodebuild[9167:67154] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUDebuggerTuckAway.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-09 10:44:54.171 xcodebuild[9168:67157] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/QuickLocalization.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-09 10:44:54.172 xcodebuild[9168:67157] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUDebuggerTuckAway.xcplugin' not present in DVTPlugInCompatibilityUUIDs
: Building libwebrtc ... 
ninja: Entering directory `out/Release'
[396/630] OBJCXX obj/webrtc/base/rtc_base.iosfilesystem.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/webrtc/base/rtc_base.iosfilesystem.o.d -DV8_DEPRECATION_WARNINGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=218707 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DENABLE_LOAD_COMPLETION_HACKS=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DEXPAT_RELATIVE_PATH -DWEBRTC_MODULE_UTILITY_VIDEO -DWEBRTC_POSIX -DWEBRTC_MAC -DFEATURE_ENABLE_SSL -DLOGGING=1 -DUSE_WEBRTC_DEV_BRANCH -DSSL_USE_OPENSSL -DHAVE_OPENSSL_SSL_H -DCARBON_DEPRECATED=YES -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -I../../third_party/jsoncpp/overrides/include -I../../third_party/jsoncpp/source/include -I../../chromium/src/third_party/jsoncpp/overrides/include -I../../chromium/src/third_party/jsoncpp/source/include -I../../chromium/src/third_party/boringssl/src/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -Wnewline-eof -mmacosx-version-min=10.6 -arch x86_64 -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -std=c++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -fcolor-diagnostics -fno-strict-aliasing -Wobjc-missing-property-synthesis -fobjc-call-cxx-cdtors  -c ../../webrtc/base/iosfilesystem.mm -o obj/webrtc/base/rtc_base.iosfilesystem.o
In file included from ../../webrtc/base/iosfilesystem.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: error: expected a type
- (id)copyWithZone:(nullable NSZone *)zone;
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:25:28: error: expected a type
- (id)mutableCopyWithZone:(nullable NSZone *)zone;
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:32:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder; // NS_DESIGNATED_INITIALIZER
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:53:4: error: expected a type
- (nullable id)replacementObjectForCoder:(NSCoder *)aCoder;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:54:4: error: expected a type
- (nullable id)awakeAfterUsingCoder:(NSCoder *)aDecoder NS_REPLACES_RECEIVER;
   ^
In file included from ../../webrtc/base/iosfilesystem.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSRange.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:17:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:30:42: error: expected a type
+ (NSValue *)valueWithNonretainedObject:(nullable id)anObject;
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:31:12: error: unknown property attribute 'nullable'
@property (nullable, readonly) id nonretainedObjectValue;
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:33:32: error: expected a type
+ (NSValue *)valueWithPointer:(nullable const void *)pointer;
                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:34:12: error: unknown property attribute 'nullable'
@property (nullable, readonly) void *pointerValue;
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:42:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSValue.h:81:38: error: expected a type
- (NSString *)descriptionWithLocale:(nullable id)locale;
                                     ^
In file included from ../../webrtc/base/iosfilesystem.mm:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSPathUtilities.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:23: error: expected ';' after @class
@class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:24: error: cannot find protocol declaration for 'ObjectType'
@class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:12:35: error: expected unqualified-id
@class NSData, NSArray<ObjectType>, NSDictionary<KeyType, ObjectType>, NSCharacterSet, NSURL, NSError, NSLocale;
                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:82:4: error: expected a type
- (nullable instancetype)initWithCoder:(NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;
   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:109:123: error: expected a type
- (NSComparisonResult)compare:(NSString *)string options:(NSStringCompareOptions)mask range:(NSRange)compareRange locale:(nullable id)locale; // locale arg used to be a dictionary pre-Leopard. We now accept NSLocale. Assumes the current locale if non-nil and non-NSLocale. nil continues to mean canonical compare, which doesn't depend on user's locale choice.
                                                                                                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:147:123: error: expected a type
- (NSRange)rangeOfString:(NSString *)searchString options:(NSStringCompareOptions)mask range:(NSRange)searchRange locale:(nullable NSLocale *)locale NS_AVAILABLE(10_5, 2_0);
                                                                                                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:151:37: error: expected a type
- (NSRange)rangeOfCharacterFromSet:(NSCharacterSet *)searchSet;
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[396/630] CXX obj/webrtc/base/rtc_base.httpserver.o
ninja: build stopped: subcommand failed.
ERROR: 1 null 

make: *** [/dev/null] Error 255
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/jeanlebrument/.nvm/versions/node/v5.0.0/bin/node" "/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64/wrtc.node" "--module_name=wrtc" "--module_path=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64"
gyp ERR! cwd /Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jeanlebrument/.nvm/versions/node/v5.0.0/bin/node /Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64/wrtc.node --module_name=wrtc --module_path=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/Users/jeanlebrument/.nvm/versions/node/v5.0.0/bin/node" "/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/Users/jeanlebrument/.nvm/versions/node/v5.0.0/bin/node /Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64/wrtc.node --module_name=wrtc --module_path=/Users/jeanlebrument/Documents/Developments/SendMessageToContact/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-darwin-x64' (1)
ReactNativeFluxBoilerplate@0.0.1 /Users/jeanlebrument/Documents/Developments/SendMessageToContact
├─┬ babel-core@5.8.33
│ └─┬ regenerator@0.8.40
│   └─┬ commoner@0.10.4
│     └── q@1.4.1 
├── localStorage@1.0.3  extraneous
├── pubnub@3.7.0  extraneous
├── q@1.4.1  extraneous
├─┬ react-native@0.13.2
│ ├─┬ jstransform@11.0.3
│ │ └─┬ commoner@0.10.4
│ │   └── q@1.4.1 
│ ├─┬ react-tools@0.14.0-beta1 (git://github.com/facebook/react.git#b4e74e38e43ac53af8acd62c78c9213be0194245)
│ │ └─┬ commoner@0.10.4
│ │   └── q@1.4.1 
│ └─┬ regenerator@0.8.42
│   └─┬ commoner@0.10.4
│     └── q@1.4.1 
├── sinch-ticketgen@0.0.6  extraneous
└── xmlhttprequest@1.8.0  extraneous

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/jeanlebrument/.nvm/versions/node/v5.0.0/bin/node" "/Users/jeanlebrument/.nvm/versions/node/v5.0.0/bin/npm" "i" "sinch-rtc" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.55 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.55 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeanlebrument/Documents/Developments/SendMessageToContact/npm-debug.log
```

From what I found on Google, I guess the problem come from WebRTC and there is potentially a fix here: https://groups.google.com/forum/#!topic/discuss-webrtc/6T1JiiSwunU

Best,
Jean

**Comment by josefrichter** [comment] 2015-12-07 22:32
@JeanLebrument were you able to resolve this, please?

**Comment by JeanLebrument** [comment] 2015-12-08 12:11
Nope, I need to use Sinch in a React-Native project so I ended up by creating a Bridge Objc to JS to be able to use the Sinch iOS SDK in my JS code.

**Comment by josefrichter** [comment] 2015-12-08 12:14
@JeanLebrument I see. Can you share that, so that I, or Sinch guys, can build on top of that, please? Thank you!

**Comment by JeanLebrument** [comment] 2015-12-08 14:24
Unfortunately, for now the code that permits that is coupled to private code used by my current company. 
By the way the bridge is only usable in a React-Native project since I'm using native bridge module provided by the React-Native library. More informations here: https://facebook.github.io/react-native/docs/native-modules-ios.html

**Comment by its2mc** [comment] 2016-05-13 04:46
Hey, I have the same issue.. and its 5 months down he line... 
`../../nan/nan.h:575:67: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((char*)data), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:579:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:586:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/wrtc/src/binding.o] Error 1
make: Leaving directory `/home/ubuntu/app/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/app/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/usr/bin/nodejs" "/home/ubuntu/app/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/app/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v48-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/home/ubuntu/app/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v48-linux-x64"
gyp ERR! cwd /home/ubuntu/app/node_modules/wrtc
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/ubuntu/app/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/app/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v48-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/ubuntu/app/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/app/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 3.13.0-74-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/ubuntu/app/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/app/node_modules/wrtc
node-pre-gyp ERR! node -v v6.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/ubuntu/app/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/app/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v48-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/ubuntu/app/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v48-linux-x64' (1)
/home/ubuntu/app
├── cheerio@0.20.0 
├── express@4.13.4 
└── request@2.72.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "sinch-rtc"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.55 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.55 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wrtc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/app/npm-debug.log
`

**Comment by its2mc** [comment] 2016-05-13 04:47
I am trying to decide on which IM platform to use at our startup.. but if your code maintenance is slow then I cannot use you guys..

**Comment by its2mc** [comment] 2016-05-13 04:48
I am open to contributing if thats an option

**Comment by cahlbin** [comment] 2016-05-13 14:56
@its2mc

First I'd like to apologise for the slow response on this, no good excuse for that.

We will not be able to prioritise this at the so we are unfortunately dependent on a fix in the upstream project (https://github.com/js-platform/node-webrtc). 

The issue is tracked in upstream as:
https://github.com/js-platform/node-webrtc/issues/226
https://github.com/js-platform/node-webrtc/issues/255

We are more than willing to roll in an updated version of the node wrtc dependency if the build issue is resolved by your contribution.

**Comment by bpevangelista** [comment] 2016-05-19 16:50
+1 Same issue here

**Comment by mirague** [comment] 2016-05-28 14:37
+1 we got the same thing

**Comment by Tantawi** [comment] 2017-10-17 08:46
Hi, The latest release should have that bug fixed. Thank you!

**Closed by Tantawi** 2017-10-17 08:46 UTC
