### ISSUE TITLE
can not install with npm

### ISSUE THREAD

**Issue by raminious** [sinch/sinch-js-rtc#4] opened 2016-02-28 09:19 UTC
Can not install sinch-rtc with npm

```
npm install --save sinch-rtc
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> wrtc@0.0.55 install /var/node/teatalk/web-react/node_modules/wrtc
> node-pre-gyp install --fallback-to-build
```

And then nothing happening

node -v = 5.7.0
npm -v = 3.6.0

**Comment by raminious** [comment] 2016-02-28 10:02
```
npm install sinch-rtc
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> wrtc@0.0.55 install /home/ramin/Development/nodejs/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/ramin/Development/nodejs/node_modules/wrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=linux CONFIGURATION=Release PYTHON=python MODULE_PATH=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64
: Preparing directories ... 
: Cloning depot_tools ... 
Cloning into 'depot_tools'...
POST git-upload-pack (205 bytes)
POST git-upload-pack (214 bytes)
remote: Counting objects: 986, done
remote: Finding sources: 100% (986/986)
remote: Total 986 (delta 130), reused 551 (delta 130)
Receiving objects: 100% (986/986), 3.00 MiB | 152.00 KiB/s, done.
Resolving deltas: 100% (130/130), done.
Checking connectivity... done.
: Cloning libwebrtc ... 
Cloning into 'libwebrtc'...
POST git-upload-pack (205 bytes)
POST git-upload-pack (214 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8730/8730), done.
remote: Total 11018 (delta 1803), reused 9934 (delta 1651), pack-reused 0
Receiving objects: 100% (11018/11018), 18.21 MiB | 172.00 KiB/s, done.
Resolving deltas: 100% (1803/1803), done.
Checking connectivity... done.
: Updating clang ... 
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.3M  100 23.3M    0     0   157k      0  0:02:32  0:02:32 --:--:--  131k
clang 218707 unpacked
: Generating build scripts ... 
Updating projects from gyp files...
: Building libwebrtc ... 
ninja: Entering directory `out/Release'
[621/621] LINK wrtc_build
: Build complete

  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/wrtc/src/binding.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../src/datachannel.h:19,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /home/ramin/.node-gyp/5.7.0/src/node.h:42:0,
                 from ../src/binding.cc:1:
/home/ramin/.node-gyp/5.7.0/deps/v8/include/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/ramin/.node-gyp/5.7.0/deps/v8/include/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/datachannel.h:19:0,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:171:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:166:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:564:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:564:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:568:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:568:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:575:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:575:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/datachannel.h:19,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
/home/ramin/.node-gyp/5.7.0/src/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ramin/.node-gyp/5.7.0/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/ramin/.node-gyp/5.7.0/src/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ramin/.node-gyp/5.7.0/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/datachannel.h:19:0,
                 from ../src/peerconnection.h:17,
                 from ../src/binding.cc:6:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:579:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:586:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
wrtc.target.mk:164: recipe for target 'Release/obj.target/wrtc/src/binding.o' failed
make: *** [Release/obj.target/wrtc/src/binding.o] Error 1
make: Leaving directory '/home/ramin/Development/nodejs/node_modules/wrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ramin/Development/nodejs/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-100.fc21.x86_64
gyp ERR! command "/home/ramin/.nvm/versions/node/v5.7.0/bin/node" "/home/ramin/Development/nodejs/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64/wrtc.node" "--module_name=wrtc" "--module_path=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64"
gyp ERR! cwd /home/ramin/Development/nodejs/node_modules/wrtc
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/ramin/.nvm/versions/node/v5.7.0/bin/node /home/ramin/Development/nodejs/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ramin/Development/nodejs/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.1.13-100.fc21.x86_64
node-pre-gyp ERR! command "/home/ramin/.nvm/versions/node/v5.7.0/bin/node" "/home/ramin/Development/nodejs/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ramin/Development/nodejs/node_modules/wrtc
node-pre-gyp ERR! node -v v5.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/home/ramin/.nvm/versions/node/v5.7.0/bin/node /home/ramin/Development/nodejs/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64/wrtc.node --module_name=wrtc --module_path=/home/ramin/Development/nodejs/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v47-linux-x64' (1)
/home/ramin/Development/nodejs
├── koa@2.0.0-alpha.3 
├── localStorage@1.0.3 
├── mock-kue@0.0.8 
├─┬ pubnub@3.7.0 
│ └── agentkeepalive@0.2.4 
├── sinch@0.4.0 
├── sinch-auth@0.0.1 
├── sinch-messaging@0.0.1 
├─┬ sinch-ticketgen@0.0.6 
│ ├── atob@1.1.3 
│ ├── btoa@1.1.2 
│ └── crypto-js@3.1.6 
├── wappalyzer@2.0.4 
└── xmlhttprequest@1.8.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/ramin/Development/nodejs/package.json'
npm WARN nodejs No description
npm WARN nodejs No repository field.
npm WARN nodejs No README data
npm WARN nodejs No license field.
npm ERR! Linux 4.1.13-100.fc21.x86_64
npm ERR! argv "/home/ramin/.nvm/versions/node/v5.7.0/bin/node" "/home/ramin/.nvm/versions/node/v5.7.0/bin/npm" "install" "sinch-rtc"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.55 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.55 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wrtc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ramin/Development/nodejs/npm-debug.log


```

**Comment by Nemant** [comment] 2016-04-10 08:56
+1 sinch may have just lost a very valuable customer

**Comment by its2mc** [comment] 2016-05-13 04:49
Sinch just lost many valuable customers.. Developer neglect..

**Comment by cahlbin** [comment] 2016-05-13 14:59
Looks like this issue has the same root cause as #1. Closing this issue and tracking in #1 instead.

**Closed by cahlbin** 2016-05-13 14:59 UTC
